title: "Data Analytics Lab"
description: "UNIST Data Analytics Lab"
url: "https://unist-da.github.io"
baseurl: "/DA-lab-page-heeyoon"   # project site

theme: null
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  members:
    output: true
    permalink: /members/:name/
  publications:
    output: true
    permalink: /research/:name/

nav:
  - title: "About"
    url: /about/
  - title: "Members"
    url: /members/
  - title: "Research"
    url: /research/
  - title: "Activity"
    url: /activity/

nav_ko:
  - title: "소개"
    url: /ko/about/
  - title: "구성원"
    url: /ko/members/
  - title: "연구"
    url: /ko/research/
  - title: "활동"
    url: /ko/activity/
